name=Voltino TriSense
version=1.2.0
author=VoltinoLabs (Tomas Michal)
maintainer=Tomas Michal
sentence=Advanced Sensor Fusion library for Voltino TriSense modules (ICM42688P, AK09918C, BMP580).
paragraph=Provides high-performance driver and fusion algorithms for the TriSense board. Features include: Advanced FIFO draining for lag-free integration, Real-Time RC Oscillator ODR Drift Tracking, Gimbal-lock immune Quaternion Math, 10MHz SPI Turbo mode, 6-point Accelerometer calibration (Sphere Fit), and Hard/Soft Iron Mag calibration. Dynamic hardware FPU optimization automatically scales precision (float/double) for platforms like Raspberry Pi Pico 2 (RP2350) and ESP32.
category=Sensors
url=https://github.com/Tomasraketak/TriSense
architectures=*
includes=TriSense.h
dependencies=
license=MIT